### PR TITLE
Quick fix for Sozin comet causing exceptions

### PR DESCRIPTION
**Pull request by Mowstyl**
When a player is on a Nether or The End environment world and you have RPG plugin, a nullpointerexception is thrown. I think it's now fixed, needs testing.
I've also removed eclipse files and updated .gitignore.

### CODE REVIEW

**Comment by Simplicitee** [comment]
Removing code causing a NPE is no way to fix it. If you could supply the NPE a fix could be made along with the other changes that are in the works.

**Comment by Mowstyl** [comment]
The problem was caused by Nether and The End worlds not being added to the marker hashmap. The code I commented was what stopped them to be added to marker. I know I could've also made a pull request to the WIP branch of projectkorra to add an if where I check whether they are in marker or not before trying to call it's method, but I think it's prefferable to remove the check from this plugin rather than editing the core just because of one old addon.
The nullpointerexception was caused in the coreplugin, so I didn't remove the code that caused it, I added the worlds needed to fix it. I don't know any different way to fix it, I'm not used with java.

**Comment by FinnBueno** [comment]
Could you also show the error perhaps? You just said it throws an error and that your "fix" needs testing however we have no clue if this error is even caused by that.

**Comment by Mowstyl** [comment]
Sorry, I forgot to send the stacktrace.

[07:01:23] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to ProjectKorra v1.8.6
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[paperclip.jar:git-Paper-1320]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[paperclip.jar:git-Paper-1320]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[paperclip.jar:git-Paper-1320]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515) ~[paperclip.jar:git-Paper-1320]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:500) ~[paperclip.jar:git-Paper-1320]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:692) ~[paperclip.jar:git-Paper-1320]
	at net.minecraft.server.v1_12_R1.PacketPlayInFlying.a(SourceFile:126) ~[paperclip.jar:git-Paper-1320]
	at net.minecraft.server.v1_12_R1.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) ~[paperclip.jar:git-Paper-1320]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[paperclip.jar:git-Paper-1320]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [paperclip.jar:git-Paper-1320]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843) [paperclip.jar:git-Paper-1320]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [paperclip.jar:git-Paper-1320]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [paperclip.jar:git-Paper-1320]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [paperclip.jar:git-Paper-1320]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.NullPointerException
	at com.projectkorra.projectkorra.ability.ElementalAbility.isSozinsComet(ElementalAbility.java:219) ~[?:?]
	at com.projectkorra.projectkorra.ability.FireAbility.getDayFactor(FireAbility.java:117) ~[?:?]
	at com.projectkorra.projectkorra.ability.FireAbility.getDayFactor(FireAbility.java:65) ~[?:?]
	at com.projectkorra.projectkorra.firebending.Illumination.<init>(Illumination.java:32) ~[?:?]
	at com.projectkorra.projectkorra.firebending.passive.FirePassive.handle(FirePassive.java:22) ~[?:?]
	at com.projectkorra.projectkorra.PKListener.onPlayerMove(PKListener.java:1141) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor828.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[paperclip.jar:git-Paper-1320]
	... 16 more

That was being spammed after I created a new world in my server with The End environment.
After the fix, it stopped happening. With needs testing I meant that I haven't properly tested wether the problem is really fixed or there are any other use case in which that exception can be thrown.
Letting the plugin add "The End" and "Nether" environment worlds should've fixed it as far as I know.
Again, I'm sorry about haven't posted the stacktrace, only talking about a not common error.

**Comment by FinnBueno** [comment]
The error happens due to the sozins commet check method, not due to what you pointed out. We'll look into this error. Thanks for your time and efforts.

**Comment by Mowstyl** [comment]
You were right, this couldn't be fixed as I did. This should be fixed in the core plugin. Thanks for your answers, I'll try to make more proper pull requests the next time. I've created a pull request to the WIP branch of the core with the fix to this problem. I've already tested it and it works.
Again, thank you for all your effort!
You are a great team!

Pd.: Link to the pull request: [https://github.com/ProjectKorra/ProjectKorra/pull/895](url)

**Pull request closed without merging**
